#!/bin/sh

REMOTE="lizen"
REMOTE_DIR="/home/vindinium"

echo "Deploy to $REMOTE:$REMOTE_DIR"

sbt ";stage;exit"
if [ $? != 0 ]; then
  echo "Deploy canceled"
  exit 1
fi

RSYNC_OPTIONS=" \
  --archive \
  --force \
  --delete \
  --progress \
  --compress \
  --checksum \
  --verbose \
  --exclude conf/application.conf \
  --exclude logs \
  --exclude RUNNING_PID";

echo "Rsync scripts, binaries and assets"
stage="target/universal/stage"
rsync_command="rsync $RSYNC_OPTIONS $stage/bin $stage/lib public $REMOTE:$REMOTE_DIR"
echo "$rsync_command"
$rsync_command

# echo "Restart"
# ssh $REMOTE "service vindinium restart"

# echo "Deploy complete"
